// All site content lives here. Edit this file to add or change entries.
// category: experience | project | research | datasci | award
// status:   Shipped | In progress | Prototype | Concept | Submitted | Accepted | Private code | Completed | Ongoing
// evidence kind: code | pr | live | doc | paper | note
// cover: animated card art from js/covers.js. shots: ["assets/shots/x.png"] replaces it with real screenshots.
const GH = "https://github.com/anishtalla27";

const PROFILE = {
  name: "Anish Talla",
  tagline: "I'm a high school student interested in engineering, software, and intelligent machines.",
  intro:
    "I build operations software at TrackMyShuttle with TypeScript and PostgreSQL. My research covers robotic grasp prediction and slip detection. I contribute to Dr. David Kane's open-source data science curriculum and lead his teaching fellows. I also mentor young business owners at LittleCEOs and play classical and jazz guitar.",
  school: "Lightridge High School and the Academy of Engineering & Technology (Academies of Loudoun), Class of 2027",
  github: GH,
  email: "anish.talla99@gmail.com",
  resume: "assets/resume.pdf",
};

const CATEGORIES = {
  experience: "Experience",
  project: "Projects",
  research: "Research & engineering",
  datasci: "Data science & open source",
  award: "Awards & activities",
};

const ENTRIES = [
  // ---------------------------------------------------------------- EXPERIENCE
  {
    id: "trackmyshuttle",
    cover: "pipeline",
    title: "TrackMyShuttle",
    category: "experience",
    org: "TrackMyShuttle",
    role: "Software Engineering Intern (paid)",
    dates: "Grades 11 to 12",
    status: "Ongoing",
    privateCode: true,
    demo: "sync",
    summary:
      "I built software for staff and partners at a shuttle-tracking company. This includes a workspace with several apps, a partner portal, marketing tools, and automations that sync operations data.",
    problem:
      "Staff used Airtable bases, email, HubSpot, and manual steps to manage operations. They needed apps that made this data easier to use and kept their existing workflows working.",
    contribution:
      "I designed the system architecture, tested the apps while signed in, and checked releases. I worked with another developer on the events calendar and with staff in operations, support, and marketing.",
    tech: ["TypeScript", "React", "Vite", "Tailwind", "Node.js", "Express", "PostgreSQL", "Airtable", "Clerk", "Make", "FedEx API", "HubSpot", "Gmail API", "Replit", "AWS ECS"],
    details: [
      "TMS Hub is a TypeScript/React monorepo: separate frontends (launcher, Admin Hub, Partner Hub, Marketing Hub) over one shared backend, with shared type contracts between packages.",
      "A transactional outbox tracks PostgreSQL changes for delivery to Airtable. Idempotency checks prevent duplicate updates, and the system handles updates that newer changes have replaced. The animation on this page shows how this works.",
      "Incremental sync rewinds its cursor to catch records changed near page or time boundaries. Schema-drift checks use stable Airtable field IDs.",
      "The backend enforces permissions. Individual overrides can restrict a person's access without accidentally granting more.",
      "Reporting distinguishes missing data from a measured zero, and single-flight caching avoids duplicate concurrent loads.",
    ],
    deliverables: [
      { name: "TMS Hub", text: "An internal workspace that routes users to the apps they can access. It has nine customer lifecycle lanes, including Lead Farming, Fulfillment, Billing, Onboarding, Active, and Closure." },
      { name: "Partner Hub", text: "A portal where partners can view account details, service stages, resources, account-team information, and maps. It syncs with Airtable." },
      { name: "Marketing Hub and event calendar", text: "An events overview, event workspaces, social calendar, email schedule, task templates, tickets, and reports. I worked on making the interface easier to use while keeping the Airtable workflows." },
      { name: "GPOS prototype", text: "A configurable, multi-tenant prototype of the Global Partner Operating System. It includes a partner registry, opportunities, proposals, permissions, and audit records." },
      { name: "AI email agent", text: "Classifies incoming Gmail by category, urgency, and response need, preserves message and thread IDs, updates Airtable email logs, and links customer records." },
      { name: "Gmail follow-up tracker", text: "Tracks follow-up deadlines for labeled Gmail conversations using business days in Eastern time. Each account has its own session and queue, and PostgreSQL stores the data." },
      { name: "Growth demo and ROI system", text: "HTML/CSS/JS pages and an Express API that send form submissions to leads, ROI assessments, dashboards, and Make scenarios. I demonstrated the full system to stakeholders." },
      { name: "Fulfillment tooling", text: "FedEx label and tracking integration, a fulfillment quality tracker, a DYMO label-printing workflow, and inventory replacement tracking." },
      { name: "Automation and data sync", text: "Make blueprints for HubSpot-to-Airtable attachment sync, contract and billing-date automation, a QBR dashboard, and a geocode cache that cuts repeated location lookups." },
      { name: "Hardware", text: "Assembled and soldered GPS kits alongside the operations team." },
    ],
    outcomes: [
      "60+ corporate partners use the partner platform.",
      "Operations, support, and marketing teams use the internal tools.",
    ],
    galleryTitle: "Screens and automations",
    galleryNote: "The Hub screen is shown with a demo account.",
    gallery: [
      { src: "assets/shots/trackmyshuttle/chooser.jpg", caption: "Signing in to TMS Hub opens a workspace chooser, with one hub per team." },
      { src: "assets/shots/trackmyshuttle/fedex-automation.jpg", caption: "The FedEx label automation in Make. An Airtable webhook creates the shipment, saves tracking, and files the label in Google Drive. A failed label is saved for review instead of retried.", wide: true },
    ],
    evidence: [
      { label: "TMS Hub", url: "https://hub.trackmyshuttle.com/", kind: "live" },
      { label: "Official TrackMyShuttle website", url: "https://trackmyshuttle.com/", kind: "live" },
      { label: "Source code is private (employer-owned). See the architecture notes and animation on this page.", kind: "note" },
    ],
  },
  {
    id: "kane-ppbds",
    cover: "code",
    title: "Data Science Internship with Dr. David Kane",
    category: "experience",
    alsoIn: ["datasci"],
    org: "PPBDS",
    role: "Data Science Intern",
    dates: "2025 to 2026",
    status: "Completed",
    summary: "I contributed to Dr. David Kane's data science textbook and interactive R curriculum. My merged changes include tests and editor-extension updates for the open-source tutorial tools.",
    problem: "The textbook and its tutorials needed reliable software and lessons that let students investigate real datasets through code.",
    contribution: "I worked with Dr. David Kane on the Preceptor's Primer for Bayesian Data Science, its curriculum, and its R packages. I revised interactive lessons, wrote automated tests, and updated editor tools. The linked pull requests show my contributions to these shared projects.",
    tech: ["R", "testthat", "learnr tutorials", "Quarto", "tidymodels", "Git/GitHub", "Positron"],
    details: [
      "I contributed to the textbook and revised interactive R lessons using roughly 15 real datasets. Students use the lessons to apply definitions, run code, and draw conclusions from data.",
      "Wrote test cases for write_answers(), the tutorial.helpers function that collects student answers. Dr. Kane merged this contribution in August 2025.",
      "Reworked editor extension tooling in tutorial.helpers in a separate pull request, also merged in August 2025.",
      "I reviewed changes and worked with other contributors in the shared PPBDS GitHub repositories.",
    ],
    outcomes: ["Acknowledged as a contributor in the Preceptor's Primer for Bayesian Data Science.", "Merged contributions to tutorial.helpers: answer-processing tests and editor-extension tooling."],
    galleryTitle: "Evidence",
    gallery: [
      { src: "assets/shots/kane/pr-75.jpg", caption: "Pull request #75 to tutorial.helpers, merged by Dr. Kane in August 2025. It adds test cases for write_answers().", wide: true },
    ],
    evidence: [
      { label: "Read the textbook", url: "https://ppbds.github.io/primer/", kind: "doc", primary: true },
      { label: "My merged contributions", url: "https://github.com/PPBDS/tutorial.helpers/pulls?q=is%3Apr+is%3Amerged+author%3Aanishtalla27", kind: "pr", primary: true },
      { label: "Textbook acknowledgments", url: "https://ppbds.github.io/primer/preamble.html#acknowledgements", kind: "doc" },
      { label: "Kane's Data Science Course", url: "https://bootcamp.davidkane.info/", kind: "live" },
      { label: "Textbook repository: PPBDS/primer", url: "https://github.com/PPBDS/primer", kind: "code" },
      { label: "R package: PPBDS/tutorial.helpers", url: "https://github.com/PPBDS/tutorial.helpers", kind: "code" },
      { label: "Textbook tutorials: PPBDS/primer.tutorials", url: "https://github.com/PPBDS/primer.tutorials", kind: "code" },
      { label: "R for Data Science tutorials: PPBDS/r4ds.tutorials", url: "https://github.com/PPBDS/r4ds.tutorials", kind: "code" },
      { label: "Editor tutorials: PPBDS/vscode.tutorials", url: "https://github.com/PPBDS/vscode.tutorials", kind: "code" },
      { label: "Merged PR #75: write_answers() test cases", url: "https://github.com/PPBDS/tutorial.helpers/pull/75", kind: "pr" },
      { label: "Merged PR #81: extension changes", url: "https://github.com/PPBDS/tutorial.helpers/pull/81", kind: "pr" },
      { label: "All PPBDS repositories", url: "https://github.com/orgs/PPBDS/repositories", kind: "code" },
      { label: "My teaching-fellow role", url: "project.html?id=kane-teaching", kind: "doc" },
    ],
  },
  {
    id: "kane-teaching",
    cover: "teach",
    title: "Kane's Data Science Course",
    category: "experience",
    org: "Dr. David Kane",
    role: "Head Teaching Fellow",
    dates: "Summers, 2025 to present",
    status: "Ongoing",
    summary: "I led 6 to 8 teaching fellows in a data science course for 90+ students across three countries. We ran study halls, reviewed code, and helped students with coursework.",
    contribution: "I started as a Teaching Fellow and became Head Teaching Fellow. I assigned work to the fellows, helped students, managed the course Discord, and helped review homework and check its quality.",
    tech: ["R", "Data science", "Code review", "Git/GitHub", "Discord"],
    details: [
      "The course runs each summer.",
      "Held study halls and helped students work through R code and data science questions.",
      "I assigned work to teaching fellows, organized homework review, handled exceptions, and checked the quality of that work.",
      "Reviewed course materials and code changes with the teaching team.",
    ],
    outcomes: ["Supported 90+ students across three countries.", "Coordinated 6 to 8 teaching fellows."],
    galleryTitle: "Photos and screenshots",
    gallery: [
      { src: "assets/shots/kane/fellows-2025.jpg", caption: "The summer 2025 course team with Dr. Kane on Zoom. I am on the right in the middle row. The photo is from the textbook's acknowledgments.", wide: true },
      { src: "assets/shots/kane/course-home.jpg", caption: "The course website. The course runs for eight weeks, mostly in summer, and is free." },
    ],
    evidence: [
      { label: "Visit the course website", url: "https://bootcamp.davidkane.info/", kind: "live", primary: true },
      { label: "Head Teaching Fellow listing", url: "https://bootcamp.davidkane.info/staff.html", kind: "doc", primary: true },
      { label: "Course repository: PPBDS/bootcamp", url: "https://github.com/PPBDS/bootcamp", kind: "code" },
      { label: "Course textbook", url: "https://ppbds.github.io/primer/", kind: "doc" },
      { label: "My separate data science internship", url: "project.html?id=kane-ppbds", kind: "doc" },
    ],
  },
  {
    id: "littleceos",
    cover: "printer",
    title: "LittleCEOs",
    category: "experience",
    org: "LittleCEOs (nonprofit, Loudoun County)",
    role: "Software Development and Operations Intern, Project Developer Lead",
    dates: "July 2025 to present",
    status: "Ongoing",
    summary:
      "I built LaunchPad for young entrepreneurs and mentored students in CAD, 3D printing, and web development.",
    contribution:
      "I led development of LaunchPad, helped with workshops, and mentored students one on one. I focused on teaching students how to build their own projects.",
    tech: ["React", "TypeScript", "CAD", "3D printing"],
    details: [
      "Mentored students in CAD, 3D printing, filament selection, and web development.",
      "Working with kids who run small businesses helped me design LaunchPad's Pricing Lab and feedback tools.",
    ],
    outcomes: ["I mentored 10+ students individually.", "The platform serves 40+ young entrepreneurs."],
    evidence: [{ label: "LaunchPad project page", url: "project.html?id=launchpad", kind: "doc" }, { label: "Official Little CEOs Foundation website", url: "https://littleceos.org/", kind: "live" }],
  },
  {
    id: "coderschool",
    cover: "code",
    title: "TheCoderSchool",
    category: "experience",
    org: "TheCoderSchool Ashburn",
    role: "CodeCoach (paid)",
    dates: "May to September 2025",
    status: "Completed",
    summary: "Taught programming to K-8 students in small classes of 2 to 6.",
    contribution: "Planned and taught weekly sessions, adjusting projects to each student's level.",
    tech: ["Python", "Java", "JavaScript", "HTML", "Scratch"],
    details: ["In these small classes, every student built their own project instead of copying one from the board."],
    evidence: [{ label: "Official Ashburn school website", url: "https://www.thecoderschool.com/locations/ashburn/", kind: "live" }],
  },

  // ---------------------------------------------------------------- PROJECTS
  {
    id: "launchpad",
    cover: "chart",
    title: "LaunchPad",
    category: "project",
    org: "LittleCEOs",
    role: "Lead developer",
    dates: "2025",
    status: "Shipped",
    summary:
      "A web platform where young entrepreneurs (roughly ages 8 to 14) price products, track their business, and get AI coaching.",
    problem: "Kids selling at markets and fairs often have trouble figuring out whether they are making money. I wanted to give them tools that were easier to use than a spreadsheet.",
    contribution: "I led development through LittleCEOs. I built the frontend, adapted the layout for mobile, worked on the branding, and deployed the site.",
    tech: ["Vite", "React", "TypeScript", "Tailwind", "shadcn/ui", "React Router", "OpenRouter / Gemini", "Vercel"],
    details: [
      "Pricing Lab walks through fixed costs, variable costs, and margins for a product.",
      "Tracks sales, expenses, events, inventory, and customer reviews.",
      "The AI coach gives feedback on product ideas. Students can test business decisions in a roughly 12-week simulation.",
      "Explored running a local model in the browser (WebLLM) with a hosted fallback and rule-based behavior when no API is available.",
    ],
    outcomes: ["The platform serves 40+ young entrepreneurs."],
    videos: [
      {
        src: "assets/video/launchpad.mp4",
        poster: "assets/video/launchpad.jpg",
        shape: "wide",
        title: "Product film (52 seconds)",
        text: "A 52-second product film. The first half walks through the app using one bracelet priced from $1.00 to $6.50. The second half shows the backend: signed-in, rate-limited AI requests with offline fallbacks, a check that stops the AI from changing any numbers, and 279 passing tests. The two AI rewrites shown are examples I wrote to demonstrate that check.",
      },
    ],
    galleryTitle: "Screens from the app",
    galleryNote: "Shown with the app's sample bracelet business.",
    gallery: [
      { src: "assets/shots/launchpad/pricing.jpg", caption: "Pricing. Moving the price or sales goal updates profit, margin, and break-even." },
      { src: "assets/shots/launchpad/report-card.jpg", caption: "The report card. The same costs, price, and margin always get the same score." },
      { src: "assets/shots/launchpad/business-numbers.jpg", caption: "The report's numbers: monthly money flow, the cost of one item, and the full financial breakdown.", wide: true },
      { src: "assets/shots/launchpad/inventory.jpg", caption: "Inventory in the business tracker, with stock levels and the value of what is on hand.", wide: true },
    ],
    evidence: [
      { label: "Live site", url: "https://www.launchpad143.com/", kind: "live" },
      { label: "Source code", url: GH + "/LaunchPad", kind: "code" },
    ],
  },
  {
    id: "stringmap",
    cover: "fretboard",
    title: "StringMap",
    category: "project",
    role: "Creator",
    dates: "2026",
    status: "Shipped",
    demo: "fretboard",
    summary:
      "A native iOS guitar-learning app that connects written music, tablature, fretboard positions, and playback. Its fingering engine uses dynamic programming to pick where on the neck to play each note.",
    problem:
      "On a guitar, the same pitch can have several string and fret positions. Some fingerings are much more comfortable than others. As a classical and jazz guitarist, I wanted an app that accounts for how a passage feels to play.",
    contribution: "I designed and built the app myself, tested it on devices, handled App Store review, and made the launch materials.",
    tech: ["Swift", "SwiftUI", "MusicXML", "Dynamic programming", "Audio synthesis"],
    details: [
      "The app reads MusicXML and bundled scores, then displays notation, tablature, and fretboard positions with synthesized playback.",
      "The fingering engine generates every valid string/fret position per note and chooses a minimum-cost route through the passage. Cost includes fret movement, position shifts, string changes, stretch, and open-string preference. Complexity is O(notes × candidates²).",
      "Players can choose weights for beginner fingerings, staying in position, or minimizing movement. The engine resolves ties deterministically. A player can also lock a position and have the engine recalculate the surrounding notes.",
      "A low-D passage cannot be played as written in standard tuning. The engine reports that limitation instead of silently dropping or transposing notes. Drop D makes it playable.",
      "I tried photo-to-tab scanning but left it out of the release because it was unreliable.",
    ],
    outcomes: ["Released on the App Store, version 1.0.0 (September 2026)."],
    videos: [
      {
        src: "assets/video/stringmap-promo.mp4",
        poster: "assets/video/stringmap-promo.jpg",
        shape: "wide",
        title: "Promo video (16:9)",
        text: "A 26-second ad for the app. The screens are real App Store screenshots, the music is Minuet in G played through the app's guitar sound, and the fingerings on screen come from a port of the app's own engine.",
      },
      {
        src: "assets/video/stringmap-promo-vertical.mp4",
        poster: "assets/video/stringmap-promo-vertical.jpg",
        shape: "tall",
        title: "Vertical cut (9:16)",
        text: "The same ad, laid out vertically for TikTok and Reels.",
      },
    ],
    galleryTitle: "Screens from the App Store release",
    galleryLayout: "phones",
    gallery: [
      { src: "assets/shots/stringmap/learn.jpg", caption: "Tutorial mode: twelve short lessons, taken in order." },
      { src: "assets/shots/stringmap/chord-shape.jpg", caption: "A lesson step. The fretboard shows the chord shape with finger numbers." },
      { src: "assets/shots/stringmap/songbook-melody.jpg", caption: "A Songbook melody, with the staff, tab, and fretboard following the same note." },
      { src: "assets/shots/stringmap/songbook-chords.jpg", caption: "The same tune as chords, with a fingering for each shape." },
    ],
    evidence: [{ label: "View on the App Store", url: "https://apps.apple.com/us/app/stringmap/id6809277270", kind: "live" }, { label: "Source code", url: GH + "/StringMap", kind: "code" }],
  },
  {
    id: "meeting-transcriber",
    cover: "wave",
    title: "Meeting Transcriber",
    category: "project",
    role: "Creator",
    status: "Shipped",
    summary: "A personal macOS app that records system and microphone audio and transcribes it locally with MLX Whisper.",
    problem: "I wanted permanent, searchable transcripts without sending audio to a server.",
    contribution: "I built this myself and use it daily.",
    tech: ["macOS", "FFmpeg", "MLX Whisper", "Markdown"],
    details: [
      "The app has a searchable library, editable transcript segments, notes, and bookmarks. It supports playback from a timestamp and exports to Markdown, plain text, and SRT.",
      "Much of the work went into recovering usable audio after crashes, handling empty microphone tracks, and saving partial transcripts. I also worked on reducing repeated text in transcriptions.",
    ],
    evidence: [{ label: "Source code", url: GH + "/MeetingTranscriber", kind: "code" }],
  },

  // ---------------------------------------------------------------- RESEARCH
  {
    id: "grasp-benchmark",
    cover: "grasprect",
    title: "Robotic Grasp Prediction: Deep Learning vs. Vision-Language Models",
    category: "research",
    org: "Academy of Engineering & Technology",
    role: "Sole author",
    dates: "2026",
    status: "Accepted",
    summary:
      "I compared rule-based vision, deep learning, and GPT-4o on robotic grasp prediction under the same test conditions. I tested them on unseen objects, calculated uncertainty, and examined the errors each method made. The paper was accepted to the Teen Research Track of IEEE ICDM 2026.",
    glance: {
      text: "The trained network (ResNet18) reached 79.7% accuracy, the rule-based method 40.7%, and GPT-4o 12.4% per call. In a follow-up test, GPT-4o still struggled when it only had to choose among marked grasps rather than write coordinates.",
      bars: [
        { label: "Trained network (ResNet18)", value: 79.7 },
        { label: "Hand-written rules", value: 40.7 },
        { label: "GPT-4o, zero-shot", value: 12.4 },
      ],
      note: "Test accuracy on 123 held-out images of 35 objects, Cornell rectangle metric. The rules reached 57.7% after a post-hoc fix, and the network averaged 84.0% over three seeds in a second training round.",
    },
    problem:
      "Published grasp-prediction accuracies are hard to compare when methods use different inputs, output formats, and scoring rules. I built systems that used the same inputs and evaluation rules so I could compare them directly.",
    contribution: "I designed the test protocol, built all four systems, ran the experiments and statistical analysis, and wrote the paper myself. I revised it three times.",
    tech: ["Python", "PyTorch", "ResNet", "Faster R-CNN", "GPT-4o", "Cornell Grasping Dataset", "Clustered bootstrap", "LaTeX"],
    details: [
      "Accepted paper title: Benchmarking Rule-Based, Learned, and Zero-Shot Vision-Language Grasp Prediction Under a Unified Evaluation Protocol. The PDF linked here is a longer version titled Three Ways to Miss a Grasp.",
      "Every system gets the same 123 test images, returns the same grasp rectangle, and is scored by one implementation of the standard Cornell rectangle test.",
      "The dataset has no object IDs, so I reconstructed them to keep every physical object in only one of train, validation, or test. Statistics are computed over the 35 test objects instead of over images, which gives wider confidence intervals.",
      "I grouped errors using the same categories for all systems. The rules struggled with angle, and the network with placement and size. GPT-4o's grasp centers landed outside the labeled grasp region 53.4% of the time, compared with about 7% for the other two systems.",
      "In a follow-up experiment, GPT-4o chose from numbered grasps drawn on each image instead of writing pixel coordinates. Its accuracy stayed at chance level. This pointed to difficulty choosing a grasp, even with coordinate writing removed from the task.",
      "When I repeated the original training setup with new random seeds, the apparent difference between ResNet18 and ResNet34 turned out to be variation between runs. Testing one seed would have missed this.",
    ],
    outcomes: [
      "Accepted to the Teen Research Track of IEEE ICDM 2026, the International Conference on Data Mining (Shenyang, China, November 2026). Four program committee members reviewed it.",
      "ICDM is run by the IEEE Computer Society and is one of the top data mining conferences, ranked CORE A*. The Teen Research Track is its track for high school researchers.",
      "Test accuracy: fine-tuned ResNet18 79.7%, detector-assisted heuristic 40.7% (57.7% after a post-hoc fix), GPT-4o 12.4% per call. The ranking held under object-clustered resampling.",
      "I did this as an independent project through my school's research program at the Academy of Engineering & Technology.",
      "Submitted to the Next Gen Scholar Research Paper Competition.",
    ],
    videos: [
      {
        src: "assets/video/grasp-benchmark.mp4?v=2",
        poster: "assets/video/grasp-benchmark.jpg?v=2",
        shape: "wide",
        title: "The paper in 50 seconds",
        text: "A 50-second walkthrough of the paper: how each system works and where it fails, the results with confidence intervals, and the follow-up where GPT-4o only had to pick from marked grasps and still did no better than chance. Every rectangle, reply, and number comes from the saved predictions.",
      },
    ],
    galleryTitle: "Figures from the paper",
    gallery: [
      { src: "assets/shots/grasp/accuracy.png", caption: "Test accuracy with 95% object-clustered confidence intervals. The line inside the rules bar is its score before a post-hoc fix (40.7%).", wide: true },
      { src: "assets/shots/grasp/three-systems.jpg", caption: "All three systems on one test image. Green is the labeled grasps, red the rules, blue the trained network, and orange GPT-4o's five calls." },
      { src: "assets/shots/grasp/marked-grasps.jpg", caption: "The follow-up experiment. GPT-4o picked mark 6, along the object, on all five calls. Mark 10, across the middle, passes the test." },
    ],
    evidence: [
      { label: "Read the paper (PDF)", url: "assets/papers/grasp-benchmark.pdf", kind: "paper" },
      { label: "Code and data", url: GH + "/Vision-Based-Grasping", kind: "code" },
    ],
  },
  {
    id: "adaptive-gripper",
    cover: "gripper",
    title: "Adaptive Robotic Grasping",
    category: "research",
    org: "Academy of Engineering & Technology",
    role: "Researcher",
    dates: "2026 to 2027",
    status: "In progress",
    demo: "gripper",
    summary:
      "I'm designing a low-cost robotic gripper that uses vision, force sensors, and vibration feedback to detect slipping objects and adjust its grip.",
    problem:
      "I want to test whether inexpensive force and vibration sensors can detect slip at or before visible motion and start correcting it within 200 milliseconds. That response time is a target I have yet to test.",
    contribution: "I'm designing the apparatus, experiment, and analysis. I've finished the literature review, methods, bill of materials, and schedule.",
    tech: ["Arduino Mega", "Force-sensitive resistors", "Piezo vibration sensors", "MG996R servo", "3D printing", "OpenSCAD", "Computer vision"],
    details: [
      "The design uses a custom 3D-printed parallel-jaw gripper with one servo and compliant fingertip pads. A fixed camera provides visual ground truth.",
      "I plan to compare force-only sensing, vibration-only sensing, and the two combined.",
      "I plan to test three surface materials at 100 g, 250 g, and 400 g, then use thin plastic and foam cups for fragility tests.",
      "I'll measure precision, recall, F1, false triggers, recovery success, response time, and damage rate.",
      "The design draws on work by Romano et al., Calandra et al., and Van Wyk and Falco.",
    ],
    evidence: [{ label: "Read the design report: slip detection (PDF)", url: "assets/papers/adaptive-gripper.pdf", kind: "paper" }],
  },
  {
    "id": "near-memory",
    "cover": "chipset",
    "title": "Where the Bytes Go: The von Neumann Bottleneck",
    "category": "research",
    "role": "Independent student researcher",
    "dates": "2026",
    "status": "Completed",
    "summary": "I measured how memory bandwidth limits language-model inference on a laptop across 23 configurations. I then modeled the potential gains from processing-in-memory hardware.",
    "problem": "Generating a token requires reading the model weights from memory. How closely does memory bandwidth predict the time that takes, and would computing inside memory still help when the host already uses 4-bit weights?",
    "contribution": "I chose the research question, designed the experiments, and ran the benchmarks on my own laptop.",
    "tech": [
      "Python",
      "llama.cpp",
      "Qwen2.5",
      "Metal",
      "Quantization",
      "Roofline modeling",
      "Processing-in-memory"
    ],
    "details": [
      "Used a MacBook Air with an M4 chip and 16 GB of unified memory. Benchmarked four Qwen2.5 model sizes, from 0.5B to 7B, across up to seven weight formats, with GPU and CPU runs, thread scaling, context lengths, and batch sizes.",
      "Compared measured decode speed with a bandwidth-over-bytes baseline and fitted latency models on the 0.5B and 3B models. The 1.5B configurations were held out from fitting; the 7B configurations provided a separate blind test.",
      "Projected performance using published parameters for commercial processing-in-memory devices. These are analytical projections, not measurements on PIM hardware.",
      "The repository includes raw measurements, discarded runs, analysis scripts, figures, the paper source, and two rounds of review. You can read the paper using the link above."
    ],
    "outcomes": [
      "16-bit decode reached 83 to 95% of measured memory bandwidth divided by bytes read per token.",
      "Changing weight format altered decode speed by up to 3.0 times, while prefill changed by at most 17%.",
      "A projected 16-bit PIM device with four times the internal bandwidth gained only 1.2 to 1.4 times over the 4-bit host baseline.",
      "Results come from one laptop, one software stack, and one model family. Model quality and power consumption were not measured."
    ],
    "videos": [
      {
        "src": "assets/video/near-memory.mp4",
        "poster": "assets/video/near-memory.jpg",
        "shape": "wide",
        "title": "The paper in 58 seconds",
        "text": "A 58-second summary of the paper. It explains how memory bandwidth limits language-model inference on a laptop. It also covers the latency prediction for the held-out 7B model (3.3% mean error) and why the projected gains from processing-in-memory chips shrink when compared with a laptop using 4-bit weights. The PIM numbers are projections, not measurements."
      }
    ],
    "galleryTitle": "Figures from the paper",
    "gallery": [
      { "src": "assets/shots/near-memory/decode-vs-bytes.png", "caption": "Decode speed against weight bytes read per token. The dashed line is measured bandwidth divided by bytes, with no fitted parameters." },
      { "src": "assets/shots/near-memory/pim-gain.png", "caption": "Projected processing-in-memory speedup for Qwen2.5-3B. At r = 4, a 16-bit part gains about 3.5 times over the 16-bit host but only about 1.2 times over the 4-bit host." },
    ],
    "evidence": [
      {
        "label": "Read the paper (PDF)",
        "url": "assets/papers/near-memory.pdf",
        "kind": "paper",
        "primary": true
      },
      {
        "label": "Code, data, and methodology on GitHub",
        "url": "https://github.com/anishtalla27/Von-Neuman-Bottleneck-Research",
        "kind": "code",
        "primary": true
      }
    ]
  },
  {
    id: "vex",
    cover: "route",
    title: "VEX Robotics, Team 42075D",
    category: "research",
    role: "Autonomous programmer",
    status: "Ongoing",
    summary: "I program autonomous routines and motion control for a VEX V5 competition robot.",
    tech: ["C++", "PROS", "LemLib", "LVGL"],
    details: ["I work on the drivetrain, motion control, and hardware integration, then test and revise the routines on the field."],
    evidence: [],
  },
  {
    id: "beaverworks",
    cover: "lane",
    title: "MIT Beaver Works: Autonomous Cars",
    category: "research",
    dates: "Approx. March to May 2024",
    status: "Completed",
    summary: "Saturday program coursework on autonomous vehicles using the RACECAR platform, about 5 to 6 hours per week.",
    tech: ["Python", "Computer vision", "Motion planning", "Control"],
    details: ["Topics: navigation, control, computer vision, motion planning, and probabilistic reasoning."],
    evidence: [{ label: "Official MIT RACECAR program", url: "https://racecar.mit.edu/", kind: "live" }],
  },
  {
    id: "weather-balloon",
    cover: "balloon",
    title: "Weather Balloon Mission",
    category: "research",
    role: "Supervisor",
    status: "Completed",
    summary: "I supervised a high-altitude balloon mission with roughly 50 students. The mission used 10+ Arduino sensor systems with GPS and CO₂ tracking.",
    tech: ["Arduino", "GPS", "Sensors"],
    details: [],
    evidence: [],
  },

  // ---------------------------------------------------------------- DATA SCIENCE
  {
    id: "tutorial-forks",
    cover: "code",
    title: "PPBDS tutorial and curriculum repositories",
    category: "datasci",
    status: "Ongoing",
    summary: "These shared PPBDS packages support interactive R lessons. My internship page links to my contributions, and these repositories contain the full projects.",
    tech: ["R", "learnr", "Quarto"],
    details: [],
    evidence: [
      { label: "PPBDS/primer.tutorials", url: "https://github.com/PPBDS/primer.tutorials", kind: "code" },
      { label: "PPBDS/r4ds.tutorials", url: "https://github.com/PPBDS/r4ds.tutorials", kind: "code" },
      { label: "PPBDS/vscode.tutorials", url: "https://github.com/PPBDS/vscode.tutorials", kind: "code" },
      { label: "PPBDS/bootcamp", url: "https://github.com/PPBDS/bootcamp", kind: "code" },
    ],
  },
  {
    id: "fourth-down",
    cover: "fanchart",
    title: "Fourth Down",
    category: "datasci",
    alsoIn: ["project"],
    role: "Creator",
    dates: "2026",
    status: "Shipped",
    summary:
      "A fantasy football tool I built for one Sleeper league. It forecasts each player's weekly score with an uncertainty range and selects a legal lineup based on win probability against the opponent. It also ranks waiver pickups by how much they could improve my roster over the rest of the season.",
    problem:
      "I found plenty of fantasy football advice, but little that measured how well it worked. I wanted to test whether modeling workload and uncertainty beats using recent box scores. I evaluated it on held-out data before using it for my own lineup.",
    contribution:
      "I built this myself. I planned the evaluation first, then built the data processing, features, models, and lineup tools. I also wrote the backtest report and documented its limitations.",
    tech: ["Python", "CatBoost", "nflverse / nflreadpy", "Sleeper API", "Integer programming", "Gaussian copula", "Bootstrap confidence intervals", "Streamlit", "pytest"],
    glance: {
      text: "On 38,674 close start/sit decisions in the 2025 holdout, the model picked the higher scorer 56.2% of the time. Sleeper's projections got 55.9%, compared with 51.8% for recent box scores. The improvement over consensus was small.",
      bars: [
        { label: "Fourth Down", value: 56.2 },
        { label: "Sleeper projections", value: 55.9 },
        { label: "Recent form (EWMA)", value: 51.8 },
      ],
      note: "Same-position, same-week player pairs that the forecast rates within 3 points of each other. 50% is a coin flip.",
    },
    details: [
      "Each player has three forecasts. My CatBoost model uses past usage (targets, carries, and snap, target, and air-yard share), team volume, opponent points allowed, Vegas implied totals, usage left by inactive teammates, and depth rank. The other forecasts use Sleeper's projected stats, scored under this league's rules, and FantasyPros expert consensus rankings, converted to points with a monotone fit for each position.",
      "A non-negative stacker combines the forecasts for each position. I use the combined forecast only where it beat the best individual forecast on the 2025 holdout, with a week-block bootstrap 95% confidence interval excluding zero. This check passes for RB, WR, and K. QB and TE use Sleeper, and DEF uses my model.",
      "Prediction ranges use a model of absolute error and empirical residual distributions by position and projection level. Less predictable players get wider ranges. The 80% intervals covered 78 to 82% of outcomes in 2025. These intervals have no conformal coverage guarantee because weekly football data is not exchangeable.",
      "A Gaussian copula models correlations between players in the same game. This accounts for relationships between a quarterback and his receivers, a defense and the opposing quarterback, and a kicker and his defense.",
      "An integer program chooses a legal lineup and respects locked players. Win probability against the opponent's roster breaks ties. Waiver values estimate the rest-of-season gain to my roster, with more weight on the playoffs. The tool also gives FAAB bid ranges and lists short-term pickups.",
      "A backward as-of join makes each game available as a feature the day after it ends. This keeps a game out of its own prediction inputs. To test for leakage, one test multiplies every outcome from a cutoff onward by 7 and fails if any earlier feature changes.",
      "The scoring engine matches Sleeper's 2025 stat lines on 99.85% of player-weeks. A separate check confirms that a lineup is legal before it appears in the report.",
      "The tool reads league data without submitting roster moves. It also checks which week an injury tag applies to. While last week's games are unfinished, it flags an Out tag as belonging to that week instead of applying it to the next lineup.",
    ],
    outcomes: [
      "On the 2025 holdout, the model picked the higher scorer in 56.2% of close start/sit decisions, compared with 55.9% for Sleeper and 51.8% for recent form. Synthetic rosters averaged 120.9 lineup points per week, compared with 120.7 and 118.0. That was roughly 3 points per week above recent box scores and a fraction of a point above consensus.",
      "80% prediction intervals covered 78 to 82% of actual outcomes across all six positions.",
      "The tool runs three times a week during the season and saves every forecast before kickoff so I can check its performance later.",
      "The report explains the limits: rest-of-season values and FAAB bids are heuristics, win probabilities still need validation against saved forecasts, and I checked the 2025 holdout twice rather than once.",
    ],
    evidence: [
      { label: "Source code", url: GH + "/FantasyFootballModel", kind: "code", primary: true },
      { label: "Backtest report, with ablations and limitations", url: GH + "/FantasyFootballModel/blob/main/reports/backtest.md", kind: "doc", primary: true },
    ],
  },
  {
    id: "wharton",
    cover: "sigmoid",
    title: "Wharton HS Data Science Competition",
    category: "datasci",
    dates: "2026",
    status: "Completed",
    summary: "A reproducible Python pipeline for predicting ice-hockey outcomes. It produces team rankings, playoff matchup probabilities, and line disparity estimates.",
    problem: "Predict game outcomes from season data, and check that the predictions are calibrated.",
    contribution: "Team project. I worked on the modeling pipeline and its reproducibility checks.",
    tech: ["Python", "Logistic regression", "Calibration", "Jupyter"],
    details: [
      "Win probabilities from logistic regression feed rankings and matchup predictions.",
      "Includes calibration, robustness, and reproducibility checks so every output can be regenerated.",
    ],
    evidence: [{ label: "Source code", url: GH + "/WhartonDataScience", kind: "code" }, { label: "Official Wharton competition and challenge", url: "https://wsb.wharton.upenn.edu/wharton-data-competition/about/", kind: "live" }],
  },

  // ---------------------------------------------------------------- AWARDS
  {
    id: "case-competition",
    cover: "medal",
    title: "Harvard Crimson Global Case Competition: 1st place worldwide",
    dates: "2025",
    category: "award",
    role: "Team PowerPoint Rangers (North America)",
    status: "Completed",
    summary: "My team placed first worldwide among 1,300+ teams. We presented our Boeing strategy for 10 minutes and answered questions for 5 minutes.",
    details: [
      "Our recommendations were three initiatives named ClearSky, BlueWing, and SkyFocus.",
      "We won a $1,500 grand prize and work experience with EY.",
    ],
    tech: ["Strategy", "Financial analysis", "Presenting"],
    galleryTitle: "Evidence",
    gallery: [
      { src: "assets/shots/case/winners.jpg", caption: "The official 2025 results page, with our team in first place." },
    ],
    evidence: [
      { label: "2025 winners: my team and name", url: "https://www.casecomp.org/winning-teams-2025", kind: "doc", primary: true },
      { label: "Our winning case solution", url: "https://www.casecomp.org/top-case-solutions-2025", kind: "doc", primary: true },
      { label: "Official HCGCC website", url: "https://www.casecomp.org/", kind: "live" },
    ],
  },
  {
    id: "ey",
    title: "EY Work Experience",
    category: "experience",
    status: "Completed",
    summary: "I earned work experience with EY through the Global Case Competition. The consulting and professional development work included an autonomous-driving strategy exercise for Rivian, presented to EY partners.",
    tech: ["Consulting", "NPV analysis"],
    details: [],
    evidence: [{ label: "Related competition: 2025 winners", url: "https://www.casecomp.org/winning-teams-2025", kind: "doc" }],
  },
  {
    id: "cyber-cup",
    title: "Virginia Commonwealth Cyber Cup",
    category: "award",
    status: "Completed",
    dates: "2025",
    summary: "My six-person team placed first in the Beginner tier and had the fourth-highest score overall at the 2025 state finals.",
    tech: ["Cybersecurity", "Capture the flag"],
    details: [],
    evidence: [
      { label: "LCPS news article naming the team", url: "https://www.lcps.org/article/2126323", kind: "doc", primary: true },
      { label: "Official Virginia HS Cyber Cup website", url: "https://sites.google.com/vt.edu/commonwealth-cyber-cup/home", kind: "live" },
    ],
  },
  {
    id: "fbla",
    title: "FBLA",
    category: "award",
    status: "Completed",
    summary: "I placed second at states, then qualified for nationals and attended.",
    tech: [],
    details: [],
    evidence: [{ label: "Official Virginia FBLA website", url: "https://www.vafbla.org/", kind: "live" }],
  },
  {
    id: "tsa-software",
    title: "TSA Software Development",
    category: "award",
    status: "Completed",
    dates: "2026",
    summary: "Our team placed fourth in Software Development at the 2026 Virginia TSA state conference. We qualified for nationals after one team dropped out.",
    tech: ["Swift", "SwiftUI", "Speech", "Claude API"],
    details: ["Our entry was OutfitAssist, a voice-first iOS app that helps blind and low-vision users choose outfits from a photo and a spoken request."],
    evidence: [
      { label: "2026 Virginia TSA state results", url: "https://tsavirginia.org/wp-content/uploads/2026/05/2026-Technosphere-TSA-Awards.html", kind: "doc", primary: true },
      { label: "Source code: OutfitAssist", url: GH + "/OutfitAssist", kind: "code" },
    ],
  },
  {
    id: "pavan",
    title: "PAVAN Regional Governor's School for the Arts",
    category: "award",
    status: "Completed",
    summary: "Selected by guitar audition in ninth grade.",
    tech: ["Classical guitar"],
    details: [],
    evidence: [{ label: "Official PAVAN program website", url: "https://pavangsa.org/", kind: "live" }],
  },
];

const FEATURED_ORDER = ["trackmyshuttle", "kane-ppbds", "adaptive-gripper", "grasp-benchmark"];

const ACADEMICS = [
  { area: "ACT", items: ["35 composite: 36 Math, 36 English, 33 Reading"] },
  { area: "GPA", items: ["4.62 weighted"] },
  { area: "Class standing", items: ["Summa cum laude (top 5%)"] },
  { area: "Program", items: ["Academies of Loudoun, Academy of Engineering & Technology, engineering pathway"] },
  { area: "Coursework", items: ["14 AP classes"] },
];

const SKILLS = [
  { area: "Languages", items: ["Python", "R", "Java", "JavaScript", "TypeScript", "Swift", "C++", "Arduino C++", "SQL", "HTML/CSS"] },
  { area: "Frontend and mobile", items: ["React", "Vite", "Tailwind", "shadcn/ui", "SwiftUI"] },
  { area: "Backend and data", items: ["Node.js", "Express", "PostgreSQL", "Supabase", "Airtable"] },
  { area: "APIs and operations", items: ["Gmail", "OAuth", "FedEx", "HubSpot", "Make", "Clerk", "Mapbox", "Webhooks"] },
  { area: "AI and computer vision", items: ["Claude API", "OpenRouter / Gemini", "ResNet", "MLX Whisper"] },
  { area: "Data science", items: ["tidymodels", "CatBoost", "Regression", "Cross-validation", "Bayesian modeling", "Causal inference", "Integer programming", "Bootstrap confidence intervals", "Automated tests"] },
  { area: "Robotics and hardware", items: ["PROS V5", "LemLib", "Arduino Mega", "FSRs", "Piezo sensors", "Servos", "CAD", "3D printing"] },
  { area: "Tools", items: ["Git/GitHub", "VS Code", "Positron", "Replit", "Vercel", "OpenSCAD", "FFmpeg", "LaTeX"] },
];
