// All site content lives here. Edit this file to add or change entries.
// category: experience | project | research | datasci | award
// status:   Shipped | In progress | Prototype | Concept | Submitted | Accepted | Private code | Completed | Ongoing
// evidence kind: code | pr | live | doc | paper | note
// cover: animated card art from js/covers.js. shots: ["assets/shots/x.png"] replaces it with real screenshots.
const GH = "https://github.com/anishtalla27";

const PROFILE = {
  name: "Anish Talla",
  tagline: "High school engineering student building software and studying robotic systems.",
  intro:
    "At TrackMyShuttle I build the TypeScript and PostgreSQL tools that keep company operations in sync. My research benchmarks rule-based and learned grasp prediction, and I am building a robotic gripper that detects slip from force and vibration sensing. I contribute to Dr. David Kane's open-source data science curriculum and lead his teaching fellows, mentor young business owners at LittleCEOs, and play classical and jazz guitar.",
  school: "Lightridge High School and the Academy of Engineering & Technology (Academies of Loudoun), Class of 2027",
  github: GH,
  email: "anish.talla99@gmail.com",
  resume: "assets/resume.pdf",
};

const CATEGORIES = {
  experience: "Experience",
  project: "Projects",
  research: "Research & Engineering",
  datasci: "Data Science & Open Source",
  award: "Awards & Activities",
};

const ENTRIES = [
  // ---------------------------------------------------------------- EXPERIENCE
  {
    id: "trackmyshuttle",
    cover: "pipeline",
    title: "TrackMyShuttle",
    category: "experience",
    org: "TrackMyShuttle",
    role: "Software Engineering Intern (paid)",
    dates: "Grades 11 to 12",
    status: "Ongoing",
    featured: true,
    privateCode: true,
    demo: "sync",
    summary:
      "Built internal and partner-facing software for a shuttle-tracking company: a multi-app workspace, partner portal, marketing tools, and the automations that keep operational data in sync.",
    problem:
      "Company operations were spread across Airtable bases, email, HubSpot, and manual steps. Teams needed usable applications on top of that data without breaking the workflows that already worked.",
    contribution:
      "I made the architectural decisions and directed development, with substantial AI collaboration on implementation. I was responsible for how the system should behave, for testing it in real authenticated sessions, and for release checks. Collaborators included a fellow developer on the events calendar and stakeholders across operations, support, and marketing.",
    tech: ["TypeScript", "React", "Vite", "Tailwind", "Node.js", "Express", "PostgreSQL", "Airtable", "Clerk", "Make", "FedEx API", "HubSpot", "Gmail API", "Replit", "AWS ECS"],
    details: [
      "TMS Hub is a TypeScript/React monorepo: separate frontends (launcher, Admin Hub, Partner Hub, Marketing Hub) over one shared backend, with shared type contracts between packages.",
      "A transactional outbox coordinates PostgreSQL writes with Airtable delivery, with idempotency protection and handling for superseded updates. The animation on this page shows the idea.",
      "Incremental sync uses a cursor rewind so records changed near pagination and timing boundaries are not missed, and schema-drift checks use stable Airtable field IDs.",
      "Authorization lives on the backend. Individual overrides can narrow a person's access but cannot accidentally expand it.",
      "Reporting distinguishes missing data from a measured zero, and single-flight caching avoids duplicate concurrent loads.",
    ],
    deliverables: [
      { name: "TMS Hub", text: "Internal workspace and access router with nine customer-lifecycle lanes, from Lead Farming through Fulfillment, Billing, Onboarding, Active, and Closure." },
      { name: "Partner Hub", text: "Partner-facing portal: account information, service lifecycle views, resources, account-team info, and maps, synchronized with Airtable." },
      { name: "Marketing Hub and event calendar", text: "Events overview, event workspaces, social calendar, email schedule, task templates, tickets, and reports. The goal was to keep the Airtable behavior and improve the interface." },
      { name: "GPOS prototype", text: "Global Partner Operating System: a configurable multi-tenant prototype with partner registry, opportunities, proposals, permissions, and auditability." },
      { name: "AI email agent", text: "Classifies incoming Gmail by category, urgency, and response need, preserves message and thread IDs, updates Airtable email logs, and links customer records." },
      { name: "Gmail follow-up tracker", text: "Monitors labeled conversations for follow-up deadlines on Eastern-time business days, with separate account sessions and queues and PostgreSQL persistence." },
      { name: "Growth demo and ROI system", text: "Plain HTML/CSS/JS pages with an Express API that route submissions into leads, ROI assessments, dashboards, and Make scenarios. Presented as a full stakeholder demo." },
      { name: "Fulfillment tooling", text: "FedEx label and tracking integration, a fulfillment quality tracker, a DYMO label-printing workflow, and inventory replacement tracking." },
      { name: "Automation and data plumbing", text: "Make blueprints for HubSpot-to-Airtable attachment sync, contract and billing-date automation, a QBR dashboard, and a geocode cache that cuts repeated location lookups." },
      { name: "Hardware", text: "Assembled and soldered GPS kits alongside the operations team." },
    ],
    outcomes: [
      "Partner platform in use by 60+ corporate partners.",
      "Internal tools used across operations, support, and marketing teams.",
    ],
    evidence: [
      { label: "TMS Hub", url: "https://hub.trackmyshuttle.com/", kind: "live" },
      { label: "Official TrackMyShuttle website", url: "https://trackmyshuttle.com/", kind: "live" },
      { label: "Source code is private (employer-owned). See the architecture notes and animation on this page.", kind: "note" },
    ],
  },
  {
    id: "kane-ppbds",
    cover: "code",
    title: "Data Science Internship with Dr. David Kane",
    category: "experience",
    alsoIn: ["datasci"],
    org: "PPBDS",
    role: "Data Science Intern",
    dates: "2025 to 2026",
    status: "Completed",
    featured: true,
    summary: "Contributed to Dr. David Kane's data science textbook, interactive R curriculum, and open-source tutorial tooling, including merged tests and editor-extension changes.",
    problem: "The textbook and its tutorials needed reliable software and lessons that let students investigate real datasets through code.",
    contribution: "Worked with Dr. David Kane on the Preceptor's Primer for Bayesian Data Science and its supporting curriculum and R packages. I reworked interactive lessons, wrote automated tests, and contributed editor tooling. The textbook and packages are collaborative projects; the linked pull requests show my specific software contributions.",
    tech: ["R", "testthat", "learnr tutorials", "Quarto", "tidymodels", "Git/GitHub", "Positron"],
    details: [
      "Contributed to the textbook and reworked lessons around interactive R tutorials and roughly 15 real datasets, helping students move from definitions to running code and drawing conclusions.",
      "Wrote test cases for write_answers(), the tutorial.helpers function that collects student answers. Dr. Kane merged this contribution in August 2025.",
      "Reworked editor extension tooling in tutorial.helpers in a separate pull request, also merged in August 2025.",
      "Worked within shared PPBDS repositories, reviewing changes and collaborating through GitHub.",
    ],
    outcomes: ["Acknowledged as a contributor in the Preceptor's Primer for Bayesian Data Science.", "Merged contributions to tutorial.helpers: answer-processing tests and editor-extension tooling."],
    evidence: [
      { label: "Read the textbook", url: "https://ppbds.github.io/primer/", kind: "doc", primary: true },
      { label: "My merged contributions", url: "https://github.com/PPBDS/tutorial.helpers/pulls?q=is%3Apr+is%3Amerged+author%3Aanishtalla27", kind: "pr", primary: true },
      { label: "Textbook acknowledgments", url: "https://ppbds.github.io/primer/preamble.html#acknowledgements", kind: "doc" },
      { label: "Kane's Data Science Course", url: "https://bootcamp.davidkane.info/", kind: "live" },
      { label: "Textbook repository: PPBDS/primer", url: "https://github.com/PPBDS/primer", kind: "code" },
      { label: "R package: PPBDS/tutorial.helpers", url: "https://github.com/PPBDS/tutorial.helpers", kind: "code" },
      { label: "Textbook tutorials: PPBDS/primer.tutorials", url: "https://github.com/PPBDS/primer.tutorials", kind: "code" },
      { label: "R for Data Science tutorials: PPBDS/r4ds.tutorials", url: "https://github.com/PPBDS/r4ds.tutorials", kind: "code" },
      { label: "Editor tutorials: PPBDS/vscode.tutorials", url: "https://github.com/PPBDS/vscode.tutorials", kind: "code" },
      { label: "Merged PR #75: write_answers() test cases", url: "https://github.com/PPBDS/tutorial.helpers/pull/75", kind: "pr" },
      { label: "Merged PR #81: extension changes", url: "https://github.com/PPBDS/tutorial.helpers/pull/81", kind: "pr" },
      { label: "All PPBDS repositories", url: "https://github.com/orgs/PPBDS/repositories", kind: "code" },
      { label: "My teaching-fellow role", url: "project.html?id=kane-teaching", kind: "doc" },
    ],
  },
  {
    id: "kane-teaching",
    cover: "teach",
    title: "Kane's Data Science Course",
    category: "experience",
    org: "Dr. David Kane",
    role: "Head Teaching Fellow",
    dates: "Summers, 2025 to present",
    status: "Ongoing",
    summary: "Led a team of 6 to 8 teaching fellows supporting 90+ data science students across three countries through study halls, code review, and course support.",
    contribution: "Progressed from Teaching Fellow to Head Teaching Fellow. I coordinated fellow assignments, supported students, managed the course Discord, and helped run homework review and quality control.",
    tech: ["R", "Data science", "Code review", "Git/GitHub", "Discord"],
    details: [
      "The course runs each summer.",
      "Held study halls and helped students work through R code and data science questions.",
      "Assigned teaching fellows and coordinated homework workflows, exceptions, and quality control.",
      "Reviewed course materials and code changes with the teaching team.",
    ],
    outcomes: ["Supported 90+ students across three countries.", "Coordinated 6 to 8 teaching fellows."],
    evidence: [
      { label: "Visit the course website", url: "https://bootcamp.davidkane.info/", kind: "live", primary: true },
      { label: "Head Teaching Fellow listing", url: "https://bootcamp.davidkane.info/staff.html", kind: "doc", primary: true },
      { label: "Course repository: PPBDS/bootcamp", url: "https://github.com/PPBDS/bootcamp", kind: "code" },
      { label: "Course textbook", url: "https://ppbds.github.io/primer/", kind: "doc" },
      { label: "My separate data science internship", url: "project.html?id=kane-ppbds", kind: "doc" },
    ],
  },
  {
    id: "littleceos",
    cover: "printer",
    title: "LittleCEOs",
    category: "experience",
    org: "LittleCEOs (nonprofit, Loudoun County)",
    role: "Software Development and Operations Intern, Project Developer Lead",
    dates: "July 2025 to present",
    status: "Ongoing",
    summary:
      "Built the LaunchPad platform for young entrepreneurs and mentored students in CAD, 3D printing, and web development.",
    contribution:
      "Led development of LaunchPad, supported workshops, and mentored students one on one. The rule I held to: teach them to build it, do not build it for them.",
    tech: ["React", "TypeScript", "CAD", "3D printing"],
    details: [
      "Mentored students in CAD, 3D printing, filament selection, and web development.",
      "Working with kids who run real lemonade-stand-scale businesses shaped LaunchPad's Pricing Lab and feedback tools.",
    ],
    outcomes: ["10+ students mentored individually.", "Platform audience of 40+ young entrepreneurs."],
    evidence: [{ label: "LaunchPad project page", url: "project.html?id=launchpad", kind: "doc" }, { label: "Official Little CEOs Foundation website", url: "https://littleceos.org/", kind: "live" }],
  },
  {
    id: "coderschool",
    cover: "code",
    title: "TheCoderSchool",
    category: "experience",
    org: "TheCoderSchool Ashburn",
    role: "CodeCoach (paid)",
    dates: "May to September 2025",
    status: "Completed",
    summary: "Taught programming to K-8 students in small classes of 2 to 6.",
    contribution: "Planned and taught weekly sessions, adjusting projects to each student's level.",
    tech: ["Python", "Java", "JavaScript", "HTML", "Scratch"],
    details: ["Small-group format meant every student shipped their own project instead of copying one from the board."],
    evidence: [{ label: "Official Ashburn school website", url: "https://www.thecoderschool.com/locations/ashburn/", kind: "live" }],
  },

  // ---------------------------------------------------------------- PROJECTS
  {
    id: "stringmap",
    cover: "fretboard",
    title: "StringMap",
    category: "project",
    role: "Creator",
    dates: "2026",
    status: "Shipped",
    featured: true,
    demo: "fretboard",
    summary:
      "A native iOS guitar-learning app that connects written music, tablature, fretboard positions, and playback. Its fingering engine uses dynamic programming to pick where on the neck to play each note.",
    problem:
      "The same pitch can be played in several places on a guitar. A passage has many technically valid fingerings, but only some are comfortable. I play classical and jazz guitar, and I wanted software that reasons about this the way a player does.",
    contribution: "Solo project: design, implementation, device QA, App Store review, and launch materials.",
    tech: ["Swift", "SwiftUI", "MusicXML", "Dynamic programming", "Audio synthesis"],
    details: [
      "A structured score pipeline reads MusicXML and bundled scores, then renders notation, tablature, and a fretboard view with synthesized playback.",
      "The fingering engine generates every valid string/fret position per note and chooses a minimum-cost route through the passage. Cost includes fret movement, position shifts, string changes, stretch, and open-string preference. Complexity is O(notes × candidates²).",
      "Profiles change the weights: beginner accessibility, staying in position, or minimizing movement. Ties break deterministically, and a user can lock one position while the surrounding notes are reoptimized.",
      "A low-D passage cannot be played as written in standard tuning. The engine reports that limitation instead of silently dropping or transposing notes. Drop D makes it playable.",
      "Photo-to-tab scanning was explored and cut. It did not meet my reliability bar, so it did not ship.",
    ],
    outcomes: ["Released on the App Store, version 1.0.0 (September 2026)."],
    videos: [
      {
        src: "assets/video/stringmap-promo.mp4",
        poster: "assets/video/stringmap-promo.jpg",
        shape: "wide",
        title: "Promo video (16:9)",
        text: "A 26-second ad for the app. The screens are real App Store screenshots, the music is Minuet in G played through the app's guitar sound, and the fingerings on screen come from a port of the app's own engine.",
      },
      {
        src: "assets/video/stringmap-promo-vertical.mp4",
        poster: "assets/video/stringmap-promo-vertical.jpg",
        shape: "tall",
        title: "Vertical cut (9:16)",
        text: "The same ad, laid out vertically for TikTok and Reels.",
      },
    ],
    evidence: [{ label: "View on the App Store", url: "https://apps.apple.com/us/app/stringmap/id6809277270", kind: "live" }, { label: "Source code", url: GH + "/StringMap", kind: "code" }],
  },
  {
    id: "launchpad",
    cover: "chart",
    title: "LaunchPad",
    category: "project",
    org: "LittleCEOs",
    role: "Lead developer",
    dates: "2025",
    status: "Shipped",
    featured: true,
    summary:
      "A web platform where young entrepreneurs (roughly ages 8 to 14) price products, track their business, and get AI coaching.",
    problem: "Kids selling at markets and fairs rarely know if they are making money. They need tools sized for them, not a spreadsheet.",
    contribution: "Led development through LittleCEOs, including frontend, mobile responsiveness, branding, and deployment.",
    tech: ["Vite", "React", "TypeScript", "Tailwind", "shadcn/ui", "React Router", "OpenRouter / Gemini", "Vercel"],
    details: [
      "Pricing Lab walks through fixed costs, variable costs, and margins for a product.",
      "Tracks sales, expenses, events, inventory, and customer reviews.",
      "AI coach gives feedback on product ideas, and a roughly 12-week simulation lets students test decisions.",
      "Explored running a local model in the browser (WebLLM) with a hosted fallback and rule-based behavior when no API is available.",
    ],
    outcomes: ["Platform audience of 40+ young entrepreneurs."],
    videos: [
      {
        src: "assets/video/launchpad.mp4",
        poster: "assets/video/launchpad.jpg",
        shape: "wide",
        title: "Product film (52 seconds)",
        text: "A 52-second product film. The first half walks through the app using one bracelet priced from $1.00 to $6.50. The second half shows the backend: signed-in, rate-limited AI requests with offline fallbacks, a check that stops the AI from changing any numbers, and 279 passing tests. The two AI rewrites shown are examples I wrote to demonstrate that check.",
      },
    ],
    evidence: [
      { label: "Live site", url: "https://www.launchpad143.com/", kind: "live" },
      { label: "Source code", url: GH + "/LaunchPad", kind: "code" },
    ],
  },
  {
    id: "meeting-transcriber",
    cover: "wave",
    title: "Meeting Transcriber",
    category: "project",
    role: "Creator",
    status: "Shipped",
    summary: "A personal macOS app that records system and microphone audio and transcribes it locally with MLX Whisper.",
    problem: "I wanted permanent, searchable transcripts without sending audio to a server.",
    contribution: "Solo project, used daily.",
    tech: ["macOS", "FFmpeg", "MLX Whisper", "Markdown"],
    details: [
      "Searchable library, editable segments, notes, bookmarks, playback with timestamp seeking, and Markdown, plain-text, and SRT export.",
      "Most of the hard work was recovery: preserving usable audio after a crash, handling empty microphone tracks, saving partial transcripts, and reducing transcription repetition.",
    ],
    evidence: [{ label: "Source code", url: GH + "/MeetingTranscriber", kind: "code" }],
  },
  {
    id: "earlier-projects",
    title: "Earlier projects",
    category: "project",
    status: "Completed",
    summary: "TouchSense 2.0, a country-flag game, an ethical-scenario platformer, and an Arduino Smart Shelf. Early work that got me building.",
    tech: ["Swift", "JavaScript", "Arduino"],
    details: [],
    evidence: [{ label: "GitHub profile", url: GH, kind: "code" }],
  },

  // ---------------------------------------------------------------- RESEARCH
  {
    id: "grasp-benchmark",
    cover: "grasprect",
    title: "Robotic Grasp Prediction: Deep Learning vs. Vision-Language Models",
    category: "research",
    role: "Sole author",
    dates: "2026",
    status: "Accepted",
    featured: true,
    summary:
      "Designed a controlled benchmark comparing rule-based vision, deep learning, and GPT-4o for robotic grasp prediction. Evaluated generalization to unseen objects, quantified uncertainty, and analyzed failure modes to identify where each approach succeeds and breaks down.",
    glance: {
      text: "The trained network was correct 84% of the time, the rules 58%, and GPT-4o 12%. A follow-up experiment showed GPT-4o's problem is choosing the grasp, not writing coordinates.",
      bars: [
        { label: "Trained network (ResNet)", value: 84.0 },
        { label: "Hand-written rules", value: 57.7 },
        { label: "GPT-4o, zero-shot", value: 12.4 },
      ],
      note: "Test accuracy on 123 held-out images of 35 objects, Cornell rectangle metric.",
    },
    problem:
      "Published accuracies for grasp prediction are hard to compare because the inputs, output formats, and scoring rules change from one method to the next. I treated the comparison as a measurement problem: build one system of each kind and hold everything else fixed.",
    contribution: "Solo project. I designed the protocol, built all four systems, ran the experiments and statistics, and wrote the paper through three revision rounds.",
    tech: ["Python", "PyTorch", "ResNet", "Faster R-CNN", "GPT-4o", "Cornell Grasping Dataset", "Clustered bootstrap", "LaTeX"],
    details: [
      "Paper title: Three Ways to Miss a Grasp: A Same-Metric Comparison of Rule-Based, Learned, and Zero-Shot Vision-Language Grasp Prediction.",
      "Every system gets the same 123 test images, returns the same grasp rectangle, and is scored by one implementation of the standard Cornell rectangle test.",
      "The dataset has no object IDs, so I reconstructed them to keep every physical object in only one of train, validation, or test. Statistics are computed over the 35 test objects instead of over images, which gives wider confidence intervals.",
      "A shared failure taxonomy shows each system breaks at a different stage: the rules miss on angle, the network on placement and sizing, and GPT-4o puts more than half of its grasp centers outside the labeled region.",
      "Follow-up experiment: instead of writing pixel coordinates, GPT-4o only had to pick one of several numbered grasps drawn on the image. Its accuracy stayed at the level of random selection, so the limit is choosing the grasp, not expressing it.",
      "Rerunning the first training recipe with new seeds showed an apparent ResNet18 vs ResNet34 gap was run-to-run variation. A single-seed comparison would have reported it as a finding.",
    ],
    outcomes: [
      "Test accuracy: trained network 84.0%, rule-based heuristic 57.7%, GPT-4o 12.4%. Every paired difference is statistically significant.",
      "Accepted at the IEEE ICDM 2026 Teen Research Track (September 2026).",
      "Submitted to the Next Gen Scholar Research Paper Competition.",
    ],
    videos: [
      {
        src: "assets/video/grasp-benchmark.mp4",
        poster: "assets/video/grasp-benchmark.jpg",
        shape: "wide",
        title: "The paper in 25 seconds",
        text: "A 25-second summary of the paper. It opens on a test image where none of GPT-4o's five grasps land on the object, then shows the results and the follow-up where GPT-4o only had to pick from 12 marked grasps and still did no better than chance. Every rectangle and number comes from the saved predictions.",
      },
    ],
    evidence: [
      { label: "Read the paper (PDF)", url: "assets/papers/grasp-benchmark.pdf", kind: "paper" },
      { label: "Code and data", url: GH + "/Vision-Based-Grasping", kind: "code" },
    ],
  },
  {
    id: "adaptive-gripper",
    cover: "gripper",
    title: "Adaptive Robotic Grasping",
    category: "research",
    org: "Academy of Engineering & Technology",
    role: "Researcher",
    dates: "2026 to 2027",
    status: "In progress",
    featured: false,
    demo: "gripper",
    summary:
      "Designing a low-cost gripper to combine vision, force sensing, and vibration feedback for slip detection and recovery.",
    problem:
      "Can inexpensive force and vibration feedback detect slip at or before visible motion, and start correcting within 200 milliseconds? That number is the target, not a result.",
    contribution: "Designing the apparatus, experiment, and analysis. Literature review, methods, bill of materials, and schedule planning are done.",
    tech: ["Arduino Mega", "Force-sensitive resistors", "Piezo vibration sensors", "MG996R servo", "3D printing", "OpenSCAD", "Computer vision"],
    details: [
      "Apparatus: a custom 3D-printed parallel-jaw gripper driven by one servo, with compliant fingertip pads and a fixed camera for visual ground truth.",
      "Comparison: force-only, vibration-only, and fused sensing.",
      "Planned conditions: three surface materials at 100 g, 250 g, and 400 g, plus thin plastic and foam cups for fragility tests.",
      "Metrics: precision, recall, F1, false triggers, recovery success, response time, and damage rate.",
      "Influences include Romano et al., Calandra et al., and Van Wyk and Falco.",
    ],
    evidence: [{ label: "Read the design report: slip detection (PDF)", url: "assets/papers/adaptive-gripper.pdf", kind: "paper" }],
  },
  {
    "id": "near-memory",
    "cover": "chipset",
    "title": "Where the Bytes Go: The von Neumann Bottleneck",
    "category": "research",
    "role": "Independent student researcher",
    "dates": "2026",
    "status": "Completed",
    "summary": "Measured how memory bandwidth limits on-device language-model inference across 23 configurations, then modeled what processing-in-memory hardware could change.",
    "problem": "Generating a token requires reading the model weights from memory. How closely does memory bandwidth predict the time that takes, and would computing inside memory still help when the host already uses 4-bit weights?",
    "contribution": "Chose the research question and experimental approach, provided and operated the laptop, and reviewed the benchmark results, analytical models, and manuscript.",
    "tech": [
      "Python",
      "llama.cpp",
      "Qwen2.5",
      "Metal",
      "Quantization",
      "Roofline modeling",
      "Processing-in-memory"
    ],
    "details": [
      "Used a MacBook Air with an M4 chip and 16 GB of unified memory. Benchmarked four Qwen2.5 model sizes, from 0.5B to 7B, across up to seven weight formats, with GPU and CPU runs, thread scaling, context lengths, and batch sizes.",
      "Compared measured decode speed with a bandwidth-over-bytes baseline and fitted latency models on the 0.5B and 3B models. The 1.5B configurations were held out from fitting; the 7B configurations provided a separate blind test.",
      "Projected performance using published parameters for commercial processing-in-memory devices. These are analytical projections, not measurements on PIM hardware.",
      "The repository includes raw measurements (including the discarded runs), analysis scripts, figures, paper source, and two rounds of critical review. The manuscript is linked above."
    ],
    "outcomes": [
      "16-bit decode reached 83 to 95% of measured memory bandwidth divided by bytes read per token.",
      "Changing weight format altered decode speed by up to 3.0 times, while prefill changed by at most 17%.",
      "A projected 16-bit PIM device with four times the internal bandwidth gained only 1.2 to 1.4 times over the 4-bit host baseline.",
      "Results come from one laptop, one software stack, and one model family. Model quality and power consumption were not measured."
    ],
    "videos": [
      {
        "src": "assets/video/near-memory.mp4",
        "poster": "assets/video/near-memory.jpg",
        "shape": "wide",
        "title": "The paper in 58 seconds",
        "text": "A 58-second summary of the paper: why memory bandwidth sets how fast a laptop runs a language model, how closely a simple model predicted a 7B model it never saw (3.3% mean error), and why processing-in-memory chips help much less once the laptop runs 4-bit weights. The PIM numbers are projections, not measurements."
      }
    ],
    "evidence": [
      {
        "label": "Read the paper (PDF)",
        "url": "assets/papers/near-memory.pdf",
        "kind": "paper",
        "primary": true
      },
      {
        "label": "Code, data, and methodology on GitHub",
        "url": "https://github.com/anishtalla27/Von-Neuman-Bottleneck-Research",
        "kind": "code",
        "primary": true
      }
    ]
  },
  {
    id: "vex",
    cover: "route",
    title: "VEX Robotics, Team 42075D",
    category: "research",
    role: "Autonomous programmer",
    status: "Ongoing",
    summary: "Program autonomous routines and motion control for a VEX V5 competition robot.",
    tech: ["C++", "PROS", "LemLib", "LVGL"],
    details: ["Drivetrain and motion control, hardware integration, and a lot of iterative testing on the field."],
    evidence: [],
  },
  {
    id: "beaverworks",
    cover: "lane",
    title: "MIT Beaver Works: Autonomous Cars",
    category: "research",
    dates: "Approx. March to May 2024",
    status: "Completed",
    summary: "Saturday program coursework on autonomous vehicles using the RACECAR platform, about 5 to 6 hours per week.",
    tech: ["Python", "Computer vision", "Motion planning", "Control"],
    details: ["Topics: navigation, control, computer vision, motion planning, and probabilistic reasoning."],
    evidence: [{ label: "Official MIT RACECAR program", url: "https://racecar.mit.edu/", kind: "live" }],
  },
  {
    id: "weather-balloon",
    cover: "balloon",
    title: "Weather Balloon Mission",
    category: "research",
    role: "Supervisor",
    status: "Completed",
    summary: "Supervised a roughly 50-student high-altitude balloon mission coordinating 10+ Arduino sensor systems with GPS and CO₂ tracking.",
    tech: ["Arduino", "GPS", "Sensors"],
    details: [],
    evidence: [],
  },

  // ---------------------------------------------------------------- DATA SCIENCE
  {
    id: "wharton",
    cover: "sigmoid",
    title: "Wharton HS Data Science Competition",
    category: "datasci",
    dates: "2026",
    status: "Completed",
    featured: true,
    summary: "A reproducible Python pipeline predicting ice-hockey outcomes: team rankings, playoff matchup probabilities, and line disparity.",
    problem: "Predict game outcomes from season data, and check that the predictions are calibrated.",
    contribution: "Team project. I worked on the modeling pipeline and its reproducibility checks.",
    tech: ["Python", "Logistic regression", "Calibration", "Jupyter"],
    details: [
      "Win probabilities from logistic regression feed rankings and matchup predictions.",
      "Includes calibration, robustness, and reproducibility checks so every output can be regenerated.",
    ],
    evidence: [{ label: "Source code", url: GH + "/WhartonDataScience", kind: "code" }, { label: "Official Wharton competition and challenge", url: "https://wsb.wharton.upenn.edu/wharton-data-competition/about/", kind: "live" }],
  },
  {
    id: "fourth-down",
    cover: "fanchart",
    title: "Fourth Down",
    category: "datasci",
    alsoIn: ["project"],
    role: "Creator",
    dates: "2026",
    status: "Shipped",
    featured: true,
    summary:
      "A weekly fantasy football decision engine for one Sleeper league. It forecasts every player's week with an uncertainty range, picks a legal lineup by win probability against the actual opponent, and ranks waiver adds by what they add to this roster over the rest of the season.",
    problem:
      "Fantasy advice is everywhere and almost none of it is scored. I wanted to know whether modeling workload and uncertainty actually beats trusting recent box scores, and by how much, measured out-of-sample before I let it touch my own lineup.",
    contribution:
      "Solo project. I set the evaluation protocol first, then built the data layer, features, models, and decision layer, and wrote the backtest report, including its limitations.",
    tech: ["Python", "CatBoost", "nflverse / nflreadpy", "Sleeper API", "Integer programming", "Gaussian copula", "Bootstrap confidence intervals", "Streamlit", "pytest"],
    glance: {
      text: "On 38,674 close start/sit calls from the 2025 holdout, the model picked the higher scorer 56.2% of the time. Sleeper's own projections got 55.9%, and recent box scores 51.8%. The edge over consensus is small.",
      bars: [
        { label: "Fourth Down", value: 56.2 },
        { label: "Sleeper projections", value: 55.9 },
        { label: "Recent form (EWMA)", value: 51.8 },
      ],
      note: "Same-position, same-week player pairs that the forecast rates within 3 points of each other. 50% is a coin flip.",
    },
    details: [
      "Three forecast members per player: a CatBoost model on lagged usage (targets, carries, snap/target/air-yard share), team volume, opponent points allowed, Vegas implied totals, vacated usage from inactive teammates, and depth rank; Sleeper's projected stat components re-scored under this league's rules; and FantasyPros expert consensus rank mapped to points by a per-position monotone fit.",
      "A non-negative stacker blends the members per position, but a gate decides whether the blend ships at all. It only replaces the best single member where it beat that member on the 2025 holdout with a week-block bootstrap 95% confidence interval excluding zero. It currently passes for RB, WR, and K; QB and TE fall back to Sleeper, and DEF to my own model.",
      "Ranges come from a model of absolute error, so volatile players get wider ones, plus empirical residual shapes by position and projection level. Observed 80% coverage on 2025 was 78 to 82%. No conformal guarantee is claimed, because weekly football data is not exchangeable.",
      "Same-game correlation goes through a Gaussian copula, so a quarterback and his receivers, a defense and the opposing quarterback, and a kicker and his own defense move together in simulation instead of independently.",
      "The decision layer handles lineup choice as an integer program under legality and lock constraints, win-probability tie-breaks against the actual opponent's roster, waiver values measured as rest-of-season gain to this specific roster weighted toward the playoffs, FAAB ranges, and streamer lists.",
      "To prevent leakage, features attach to future rows by a backward as-of join on the day after each game, so a target game cannot enter its own features. A test multiplies every outcome from a cutoff onward by 7 and fails if any earlier feature moves.",
      "The scoring engine reconciles to Sleeper's own 2025 stat lines on 99.85% of player-weeks, and the brief refuses to print a lineup that fails an independent legality check.",
      "It only reads. It never submits a roster move, and injury tags are week-aware: while last week's games are still unfinished, an Out tag describes last week and gets flagged rather than applied.",
    ],
    outcomes: [
      "Measured on the 2025 holdout: 56.2% on close start/sit calls against 55.9% for Sleeper and 51.8% for recent form, and 120.9 lineup points per week on synthetic rosters against 120.7 and 118.0. That is roughly 3 points a week over trusting recent box scores, and a fraction of a point over consensus.",
      "80% prediction intervals covered 78 to 82% of actual outcomes across all six positions.",
      "Runs three times a week in season and logs every forecast to a prospective ledger before kickoff, so the live record can be checked later.",
      "Limits stated in the report: rest-of-season values and FAAB bids are heuristics, win probabilities are unverified until the ledger accumulates, and the 2025 holdout was looked at twice rather than once.",
    ],
    evidence: [
      { label: "Source code", url: GH + "/FantasyFootballModel", kind: "code", primary: true },
      { label: "Backtest report, with ablations and limitations", url: GH + "/FantasyFootballModel/blob/main/reports/backtest.md", kind: "doc", primary: true },
    ],
  },
  {
    id: "tutorial-forks",
    cover: "code",
    title: "PPBDS tutorial and curriculum repositories",
    category: "datasci",
    status: "Ongoing",
    summary: "Shared PPBDS teaching packages supporting interactive R lessons. My internship page links to my contributions; these repositories provide the broader project context.",
    tech: ["R", "learnr", "Quarto"],
    details: [],
    evidence: [
      { label: "PPBDS/primer.tutorials", url: "https://github.com/PPBDS/primer.tutorials", kind: "code" },
      { label: "PPBDS/r4ds.tutorials", url: "https://github.com/PPBDS/r4ds.tutorials", kind: "code" },
      { label: "PPBDS/vscode.tutorials", url: "https://github.com/PPBDS/vscode.tutorials", kind: "code" },
      { label: "PPBDS/bootcamp", url: "https://github.com/PPBDS/bootcamp", kind: "code" },
    ],
  },
  {
    id: "tsa-geospatial",
    title: "TSA Geospatial Technology",
    category: "datasci",
    status: "Completed",
    summary: "A portfolio analyzing the urban heat island effect in Fairfax County using publicly available NASA DEVELOP data.",
    tech: ["GIS", "Remote sensing data"],
    details: [],
    evidence: [],
  },

  // ---------------------------------------------------------------- AWARDS
  {
    id: "case-competition",
    cover: "medal",
    title: "Harvard Crimson Global Case Competition: 1st place worldwide",
    dates: "2025",
    category: "award",
    role: "Team PowerPoint Rangers (North America)",
    status: "Completed",
    featured: false,
    summary: "First place globally among 1,300+ teams with a Boeing strategy presentation: 10 minutes presenting, 5 minutes of Q&A.",
    details: [
      "Our recommendations were three initiatives named ClearSky, BlueWing, and SkyFocus.",
      "The prize included a $1,500 grand prize and work experience with EY.",
    ],
    tech: ["Strategy", "Financial analysis", "Presenting"],
    evidence: [
      { label: "2025 winners: my team and name", url: "https://www.casecomp.org/winning-teams-2025", kind: "doc", primary: true },
      { label: "Our winning case solution", url: "https://www.casecomp.org/top-case-solutions-2025", kind: "doc", primary: true },
      { label: "Official HCGCC website", url: "https://www.casecomp.org/", kind: "live" },
    ],
  },
  {
    id: "ey",
    title: "EY Work Experience",
    category: "experience",
    status: "Completed",
    summary: "Consulting and professional-development work earned through the Global Case Competition, including an autonomous-driving strategy exercise for Rivian presented to EY partners.",
    tech: ["Consulting", "NPV analysis"],
    details: [],
    evidence: [{ label: "Related competition: 2025 winners", url: "https://www.casecomp.org/winning-teams-2025", kind: "doc" }],
  },
  {
    id: "cyber-cup",
    title: "Virginia Commonwealth Cyber Cup",
    category: "award",
    status: "Completed",
    dates: "2025",
    summary: "First place in the Beginner tier and fourth-highest score overall at the 2025 state finals, on a six-person team.",
    tech: ["Cybersecurity", "Capture the flag"],
    details: [],
    evidence: [
      { label: "LCPS news article naming the team", url: "https://www.lcps.org/article/2126323", kind: "doc", primary: true },
      { label: "Official Virginia HS Cyber Cup website", url: "https://sites.google.com/vt.edu/commonwealth-cyber-cup/home", kind: "live" },
    ],
  },
  {
    id: "fbla",
    title: "FBLA",
    category: "award",
    status: "Completed",
    summary: "Second place at the state level. National qualifier and attendee.",
    tech: [],
    details: [],
    evidence: [{ label: "Official Virginia FBLA website", url: "https://www.vafbla.org/", kind: "live" }],
  },
  {
    id: "tsa-software",
    title: "TSA Software Development",
    category: "award",
    status: "Completed",
    dates: "2026",
    summary: "Fourth place in Software Development at the 2026 Virginia TSA state conference. Qualified for nationals after one team dropped.",
    tech: ["Swift", "SwiftUI", "Speech", "Claude API"],
    details: ["Our entry was OutfitAssist, a voice-first iOS app that helps blind and low-vision users choose outfits from a photo and a spoken request."],
    evidence: [
      { label: "2026 Virginia TSA state results", url: "https://tsavirginia.org/wp-content/uploads/2026/05/2026-Technosphere-TSA-Awards.html", kind: "doc", primary: true },
      { label: "Source code: OutfitAssist", url: GH + "/OutfitAssist", kind: "code" },
    ],
  },
  {
    id: "pavan",
    title: "PAVAN Regional Governor's School for the Arts",
    category: "award",
    status: "Completed",
    summary: "Selected by guitar audition in ninth grade.",
    tech: ["Classical guitar"],
    details: [],
    evidence: [{ label: "Official PAVAN program website", url: "https://pavangsa.org/", kind: "live" }],
  },
];

const FEATURED_ORDER = ["stringmap", "grasp-benchmark", "fourth-down", "trackmyshuttle", "kane-ppbds", "launchpad", "wharton"];

const ACADEMICS = [
  { area: "ACT", items: ["35 composite: 36 Math, 36 English, 33 Reading"] },
  { area: "GPA", items: ["4.62 weighted"] },
  { area: "Class standing", items: ["Summa cum laude (top 5%)"] },
  { area: "Program", items: ["Academies of Loudoun, Academy of Engineering & Technology, engineering pathway"] },
  { area: "Coursework", items: ["14 AP classes"] },
];

const SKILLS = [
  { area: "Languages", items: ["Python", "R", "Java", "JavaScript", "TypeScript", "Swift", "C++", "Arduino C++", "SQL", "HTML/CSS"] },
  { area: "Frontend and mobile", items: ["React", "Vite", "Tailwind", "shadcn/ui", "SwiftUI"] },
  { area: "Backend and data", items: ["Node.js", "Express", "PostgreSQL", "Supabase", "Airtable"] },
  { area: "APIs and operations", items: ["Gmail", "OAuth", "FedEx", "HubSpot", "Make", "Clerk", "Mapbox", "Webhooks"] },
  { area: "AI and computer vision", items: ["Claude API", "OpenRouter / Gemini", "ResNet", "MLX Whisper"] },
  { area: "Data science", items: ["tidymodels", "CatBoost", "Regression", "Cross-validation", "Bayesian modeling", "Causal inference", "Integer programming", "Bootstrap confidence intervals", "Automated tests"] },
  { area: "Robotics and hardware", items: ["PROS V5", "LemLib", "Arduino Mega", "FSRs", "Piezo sensors", "Servos", "CAD", "3D printing"] },
  { area: "Tools", items: ["Git/GitHub", "VS Code", "Positron", "Replit", "Vercel", "OpenSCAD", "FFmpeg", "LaTeX"] },
];
